### ISSUE TITLE
Add a quiet flag to pushb and popb

### ISSUE THREAD

**Issue by chmaynard** [pwoolcoc/pushb#1]
Both `git checkout` and `git switch` support the --quiet flag to suppress feedback messages. This is a request to add this flag to pushb and popb as well.

**Comment by pwoolcoc** [comment]
Not sure if this is even still relevant to you 2 years hence, but in case it is, I've added this and released it as version `0.2.3` to crates.io. Sorry for such a long delay

**Comment by chmaynard** [comment]
Thanks, this will be useful to me.
